import os
from crew import TradingCrew
from database import DatabaseManager
from notifier import TelegramNotifier
from dotenv import load_dotenv

load_dotenv()

def parse_crew_output(result):
    """
    Parse the CrewAI Pydantic output.
    Result from CrewAI with output_json is typically the Pydantic object itself
    or a string representation of it.
    """
    if hasattr(result, 'market_bias'):
        # Result is already the ManagerOutlook Pydantic object
        return {
            "summary": result.final_summary,
            "bias": result.market_bias,
            "notes": " ".join(result.key_drivers),
            "raw_obj": result
        }

    # Fallback for string output
    summary = str(result)
    bias = "NEUTRAL"
    if "BULLISH" in summary.upper(): bias = "BULLISH"
    elif "BEARISH" in summary.upper(): bias = "BEARISH"

    return {
        "summary": summary,
        "bias": bias,
        "notes": "Generated by Agentic Crew",
        "raw_obj": None
    }


def main():
    print("🚀 Starting Morning Newsletter Crew...")

    # 1. Execute the Crew
    crew_instance = TradingCrew()
    final_result = crew_instance.run()

    # 2. Parse the result
    parsed = parse_crew_output(final_result)

    # 3. Save to Supabase
    print("💾 Saving to Supabase...")
    db = DatabaseManager()
    # Note: In the first version, we'll send the final summary.
    # Full agent-level breakdown requires custom output captures in CrewAI.
    report_id = db.save_market_report(
        summary=parsed['summary'],
        bias=parsed['bias'],
        manager_notes=parsed['notes'],
        agent_results=[] # Will be populated once structured output is fully wired
    )

    # 4. Send to Telegram
    print("📲 Sending to Telegram...")
    notifier = TelegramNotifier()
    telegram_text = f"📈 *NIFTY 50 Morning Outlook*\n\nBias: *{parsed['bias']}*\n\n{parsed['summary']}"
    notifier.send_message(telegram_text)

    print("✅ Process Complete.")

if __name__ == "__main__":
    main()
